### ISSUE TITLE
PyPy :  pycurl

### ISSUE THREAD

**Issue by gst** [savoirfairelinux/shinken#2]
pycurl : https://github.com/pycurl/pycurl/issues/208

**Comment by gst** [comment]
same result as upstream: 

```
(shinken-pypy) ✔ ~/work/work/SFL/Supervision/shinken [coverage_prob|✚ 1…1⚑ 6]
gstarck@gstarck 15:53 $ python 
Python 2.7.3 (2.2.1+dfsg-1ubuntu0.2, Dec 02 2014, 23:00:55)
[PyPy 2.2.1 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``NO VCS DISCUSSIONS''
>>>> import pycurl
>>>> pycurl.Curl()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <StackOverflow object at 0x1d47148>
>>>> 
```

**Comment by gst** [comment]
double confirmation of the prob:

```
gstarck@gstarck 15:54 $ python ./shinken/daemons/arbiterdaemon.py -h
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "./shinken/daemons/arbiterdaemon.py", line 38, in <module>
    from shinken.objects.config import Config
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/objects/config.py", line 83, in <module>
    from shinken.daemon import get_cur_user, get_cur_group
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/daemon.py", line 48, in <module>
    import shinken.http_daemon
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/http_daemon.py", line 63, in <module>
    from shinken.stats import statsmgr
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/stats.py", line 204, in <module>
    statsmgr = Stats()
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/stats.py", line 67, in __init__
    self.con = HTTPClient(uri='http://kernel.shinken.io')
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/http_client.py", line 69, in __init__
    self.con = pycurl.Curl()
SystemError: <StackOverflow object at 0x1d47148>
(shinken-pypy) ✘ ~/work/work/SFL/Supervision/shinken [coverage_prob|✚ 1…1⚑ 6]
gstarck@gstarck 15:54 $ 
```

**Comment by bit2pixel** [comment]
any updates on this?
